const TCPMembers = [
    { name: "Vijayan K. Asari", organization: "University of Dayton, USA" },
    { name: "Petra Wiederhold", organization: "Av. Instituto Politécnico Nacional, Mexico" },
    { name: "Ansuman Kumar", organization: "NEHU, India" },
    { name: "Dharavath Ramesh", organization: "IIT, Dhanbad, India" },
    { name: "Badal Soni", organization: "NIT Shilchar, India" },
    { name: "Arup Kumar Pal", organization: "IIT, Dhanbad, India" },
    { name: "Tandra Pal", organization: "NIT, Durgapur, India" },
    { name: "Rajib Ghosh", organization: "National Institute of Technology Patna, India" },
    { name: "Bibhas Ch. Dhara", organization: "Jadavpur University, India" },
    { name: "Debashis De", organization: "MAKAUT, India" },
    { name: "Biswapati Jana", organization: "Vidyasagar University, India" },
    { name: "Maheshwari Prasad Singh", organization: "NIT, Patna, India" },
    { name: "Amitabha Nath", organization: "NEHU, India" },
    { name: "Bubu Bhuyan", organization: "NEHU, India" },
    { name: "Dr. Anupam Biswas", organization: "NIT, Shilchar, India" },
    { name: "Bertrand Kerautret", organization: "Lumière University Lyon 2, France" },
    { name: "Saptarsi Goswami", organization: "Calcutta University, India" },
    // { name: "Udai Pratap Rao", organization: "NIT Patna, India" },
    { name: "Soumya Sen", organization: "Calcutta University, India" },
    { name: "Anjan Bandyopadhyay", organization: "KIIT, India" },
    { name: "Saiyed Umer", organization: "Alia University, India" },
    { name: "Abhishek Singhal", organization: "Amity University, India" },
    { name: "Subrata Dutta", organization: "NIT, Jamsedpur, India" },
    { name: "Supriya Raheja", organization: "Amity University, India" },
    { name: "Koushlendra Kumar Singh", organization: "NIT, Jamsedpur, India" },
    { name: "Manoj Kr. Shukla", organization: "Amity University, India" },
    { name: "Sujit Das", organization: "Sikha o Anusandhan, India" },
    { name: "Dushyant Kumar Singh", organization: "MNIT, Alahabad, India" },
    { name: "Snehanshu Saha", organization: "BITS Pilani, Goa, India" },
    { name: "Dr. Sunirmal Khatua", organization: "Calcutta University, India" },
    { name: "Animesh Dutta", organization: "NIT Durgapur, India" },
    { name: "Sanjit Setua", organization: "Calcutta University, India" },
    { name: "SANJEEVI SRIRAM", organization: "NIT, Warangal, India" },
    { name: "Odelu Vanga", organization: "IIIT, Chittoor, India" },
    { name: "Abhishek Hazra", organization: "IIIT, Chittoor, India" },
    { name: "SAROJ KUMAR BISWAS", organization: "NIT, Silchar, India" },
    { name: "Satyaki Roy", organization: "University of Alabama in Huntsville, USA" },
    { name: "Francesco Betti Sorbelli", organization: "University of Perugia, Italy" },
    { name: "Saurav Nanda", organization: "Synopsys, Mountain View, CA, USA" },
    { name: "Anusha K", organization: "Velore Institute of Technology, India" },
    { name: "Dorsala Mallikarjun Reddy", organization: "IIIT, Chittoor, India" },
    { name: "Shameek Bhattacharjee", organization: "Western Michigan University, Kalamazoo, MI, USA" },
    { name: "M. Sridevi", organization: "NIT, Tiruchirappalli, India" },
    { name: "K.Himabindu", organization: "NIT, Andhra Pradesh, India" },
    { name: "Rajendra Prasath", organization: "IIIT, Chittoor, India" },
    { name: "Asish Bera", organization: "Birla Institute of Technology and Science, Pilani, India" },
    { name: "Annappa B", organization: "NIT Karnataka, Surathkal, India" },
    { name: "Keerthana Prasad", organization: "Manipal Academy of Higher Education, India" },
    { name: "Biswajit R Bhowmik", organization: "NIT Karnataka, Surathkal, India" },
    { name: "Pavan Kumar C", organization: "IIIT, Dharwad, India" },
    { name: "Kamlesh Tiwari", organization: "BITS Pilani, India" },
    { name: "P. Santhi Thilagam", organization: "NIT Karnataka, Surathkal, India" },
    { name: "Basabdatta Bhattacharya", organization: "Birla Institute of Technology and Science, Pilani, India" },
    { name: "Yadunath Pathak", organization: "VNIT, Nagpur, India" },
    { name: "Vinod Pachghare", organization: "COEP Technological University, Pune, India" },
    { name: "Bhupendra Singh", organization: "IIIT, Pune, India" },
    { name: "Mahendra Pratap Yadav", organization: "IIIT, Pune, India" },
    { name: "Sonam Maurya", organization: "IIIT, Pune, India" },
    { name: "Mahesh Shirole", organization: "Veermata Jijabai Technological Institute, Pune, India" },
    { name: "Sunita Dhavale", organization: "Defence Institute of Advanced Technology, Pune, India" },
    { name: "Upasana Singh", organization: "Defence Institute of Advanced Technology, Pune, India" },
    { name: "Shital Raut", organization: "Visvesvaraya National Institute of Technology, Nagpur, India" },
    { name: "Anil Kumar Singh", organization: "Motilal Nehru National Institute of Technology Allahabad, Prayagraj, India" },
    { name: "Salvatore Distefano", organization: "University of Messina, Italy" },
    { name: "Devesh C Jinwala", organization: "S V National Institute of Technology, Surat, India" },
    { name: "Pilli Emmanuel Shubhakar", organization: "Malaviya National Institute of Technology Jaipur, India" },
    { name: "Ramesh Babu Battula", organization: "Malaviya National Institute of Technology Jaipur, India" },
    { name: "Yogesh Kumar", organization: "Pandit Deendayal Energy University, Gandhinagar, India" },
    { name: "UDAI PRATAP RAO", organization: "National Institute of Technology Patna, India" },
    { name: "Pramit Mazumdar", organization: "Indian Institute of Information Technology, Vadodara, India" },
    { name: "Sumit Kalra", organization: "IIT, Jodhpur, India" },
    { name: "Debdatta Kandar", organization: "North Eastern Hill University, India" },
    { name: "Sujit Das", organization: "National Institute of Technology Warangal, India" },
    { name: "Subbulakshmi T", organization: "Velore Institute of Technology, India" },
    { name: "Maheswari.R", organization: "Velore Institute of Technology, India" },
    { name: "Arnab Kumar Maji", organization: "North Eastern Hill University, India" },
    { name: "Janaki Meena Murugan", organization: "Velore Institute of Technology, India" },
    { name: "Pradeep Kumar TS", organization: "Velore Institute of Technology, India" },
    { name: "Mithlesh Arya", organization: "Swami Keshvanand Institute of Technology, Jaipur, India" },
    { name: "Sutanu Chakraborti", organization: "IIT, Madras, India" },
    { name: "Sunil B. Mane", organization: "COEP Technological University, Pune, India" },
    { name: "Megha Gupta", organization: "Swami Keshvanand Institute of Technology, Management & Gramothan, Jaipur, India" },
    { name: "Anindya Halder", organization: "North-Eastern Hill University, India" },
    { name: "Nitesh K Bharadwaj", organization: "IIIT, Pune, India" },
    { name: "Nithya Balasubramanian", organization: "NIT, Trichy, India" },
    { name: "Somitra Kr. Sanadhya", organization: "IIT Jodhpur, India" },
    { name: "ANIL KUMAR VERMA", organization: "Thapar University, India" },
    { name: "Mrityunjay Singh", organization: "IIIT, Una, India" },
    { name: "Shefali Arora Chouhan", organization: "NIT, Jalandhar, India" },
    { name: "Jaspal Kaur Saini", organization: "IIIT, Una, India" },
    { name: "Kanu Goel", organization: "Punjab Engineering College, Chandigarh, India" },
    { name: "Vijay Kumar", organization: "NIT, Jalandhar, India" },
    { name: "Somesula Manoj Kumar", organization: "NIT, Jalandhar, India" },
    { name: "Prashant Kumar", organization: "NIT, Jalandhar, India" },
    { name: "Krishan Kumar", organization: "NIT, KURUKSHETRA, India" },
    { name: "Anoop Patel", organization: "NIT, KURUKSHETRA, India" },
    { name: "Dhiren patel", organization: "NIT, Surat, India" },
    { name: "Shveta Mahajan", organization: "NIT, Jalandhar, India" },
    { name: "Satnam Kaur", organization: "Punjab Engineering College, India" },
    { name: "Vikram Singh", organization: "NIT, KURUKSHETRA, India" },
    { name: "Virender Ranga", organization: "NIT, KURUKSHETRA, India" },
    { name: "Kriti Bhushan", organization: "NIT, KURUKSHETRA, India" },
    { name: "Pratistha Verma", organization: "NIT, KURUKSHETRA, India" },
    { name: "Ayoub Khan", organization: "University of Bisha, Bisha, Kingdom of Saudi Arabia" },
    { name: "Avani Vyas", organization: "NIT, Jalandhar, India" },
    { name: "Sushil Kumar", organization: "NIT, KURUKSHETRA, India" },
    { name: "Deepak Ranjan Nayak", organization: "Malaviya National Institute of Technology Jaipur, India" },
    { name: "Deepak Mishra", organization: "IIT, Jodhpur, India" },
    { name: "Rituraj Soni", organization: "Engineering College Bikaner, India" },
    { name: "Parveen Kumar", organization: "NIT, Kurukshetra, India" },
    { name: "Swapan Maiti", organization: "VNIT, Nagpur, India" },
    { name: "Vincenzo Piuri", organization: "University of Milan, Italy" },
    { name: "Niyati Baliyan", organization: "NIT, Kurukshetra, India" },
    { name: "Vijay Kumar", organization: "NIT, Hamirpur, India" },
    { name: "Jaspal Kaur Saini", organization: "IIIT, Una, India" },
    { name: "Mrityunjay Singh", organization: "IIIT, Una, India" },
    { name: "Pardeep Singh", organization: "NIT, Hamirpur, India" },
    { name: "Shashi Gurung", organization: "Govt. Hydro Engineering College, India" },
    { name: "Ajay Kumar Mallick", organization: "NIT, Hamirpur, India" },
    { name: "Nisha Chaurasia", organization: "NIT, Jalandhar, India" },
    { name: "Pranav Kumar Chaudhary", organization: "Senior SDE, Amazon" },
    { name: "Arindam Biswas", organization: "Kazi Nazrul University, India" },
    { name: "Christoph Meinel", organization: "German University of Digital Science" },
    { name: "Rolando Herrero", organization: "Northeastern University, USA" },
    { name: 'Sajedul Talukder', organization: 'Southern Illinois University' },
    { name: 'A. Vijaya Lakshmi', organization: 'B V Raju Institute of Technology, India' },
    { name: 'Dr. Kevin Wang', organization: 'NeuroSoph Development Inc, Edmonton, Canada' },
    { name: 'Kevin Wang', organization: 'NeuroSoph Development Inc, Edmonton, Canada' },
    { name: 'Rebanta Mitra', organization: 'NVIDIA Corporation, San Jose, California, USA' },
    { name: 'Geeta Pyne', organization: 'TIAA, San Jose, California, USA' },
    { name: 'Khan Wahid', organization: 'University of Saskatchewan, Canada' },
    { name: 'Nilanjan Ray', organization: 'University of Alberta, Canada' },
    { name: 'Hongming Xu', organization: 'Dalian University of Technology, China' },
    { name: 'Keshav Dahal', organization: 'University of the West of Scotland High Street, UK' },
    { name: 'Mueen Uddin', organization: 'University of Doha for Science and Technology, Qatar' },    
    { name: 'Sajedul Talukder' , organization: 'Southern Illinois University'},
    {name : 'A. Vijaya Lakshmi', organization: 'B V Raju Institute of Technology, India'},
    {name: 'Banafsheh Rekabdar' , organization: 'Portland State University'},
    {name: 'Aloizio Pereira da Silva', organization: 'Commonwealth Cyber Initaitive, Virginia Tech'},
    {name:'Goutham Reddy', organization: 'University of Illinois, Springfield USA' },
    {name: 'Rabindra Bista' , organization: 'Katmandu University, Nepal'},
    {name: 'Kuo-Hui Yeh' , organization: 'National Yang Ming Chiao Tung University, Taiwan'},
    {name: 'Raveendra Babu Ponnuru' , organization: 'Cleveland State University, USA'},
    { name: "Keshav Dahal", organization: "University of the West of Scotland" },
    { name: "Mueen Uddin", organization: "University of Doha for Science & Technology Qatar" },
    { name: "Mohammad Wazid", organization: "Graphic Era Deemed to be University, Dehradun, India" },
    { name: "Tso Raylin", organization: "National Chengchi University, Taiwan" },
    { name: "Cheng-Chi Lee", organization: "Fu Jen Catholic University, Taiwan" },
    { name: "Arijit Karati", organization: "National Sun Yat-sen University, Taiwan" },
    { name: "Joy Dutta", organization: "Khalifa University of Science and Technology, UAE" },
    { name: "Alawi A. Al-saggaf", organization: "King Fahd University of Petroleum and Minerals, Saudi Arabia" },
    { name: "Marko Hölbl", organization: "University of Maribor, Slovenija" },
    { name: "Fagen Li", organization: "University of Electronic Science and Technology of China, P.R.China" },
    { name: "Akber Ali Khan", organization: "IIMT College of Engineering, Greater Noida, India" },
    { name: 'Chun-Ta Li', organization: "Fu Jen Catholic University, Taiwan"},
    {name: 'Debiao He', organization: 'Wuhan University, China'},
    
];

export default TCPMembers;